defaults:
  # Logging and checkpoint configurations
  logdir: logs/drqn/{timestamp}
  device: cuda
  filter: '.*'

  train:
    steps: 500000  # Total number of training steps
    log_every: 10000  # Log metrics every N steps
    learning_rate: 1e-4 # Learning rate for Adam optimizer
    batch_size: 32        # Batch size for training
    buffer_capacity: 500000 # Maximum number of trajectories in replay buffer
    train_every: 81       # Train after every N environment steps
    target_period: 810 # Update target every N steps
    num_gradient_steps: 10 # Number of gradient steps per training update
    save_every: 50000   # Save checkpoint every N steps
    epsilon: 0.2         # Exploration rate
    gamma: 0.99          # Discount factor
    num_envs: 1

  # Environment configurations
  env:
    name: "mordor-hike-easy-v0"
    kwargs: "{}"
  
  # DRQN specific configurations
  drqn:
    hidden_size: 32      # Size of GRU hidden layer
    num_layers: 2         # Number of GRU layers
  
  # Random seed for reproducibility
  seed: 42
  
  # Weights & Biases logging configuration
  wandb:
    project: "powm"  # Set project name to enable W&B logging
    group: ""
    name: ""

debug:
  # Minimal configuration for debugging
  run:
    steps: 10000
    log_every: 100
  wandb:
    project: ""