Task: "JointTrainAgent"

BasicSettings:
  Seed: 0
  ImageSize: 64
  ReplayBufferOnGPU: True

JointTrainAgent:
  SampleMaxSteps: 202000
  BufferMaxLength: 200000
  BufferWarmUp: 1024
  NumEnvs: 1
  BatchSize: 16
  DemonstrationBatchSize: 4
  BatchLength: 64
  ImagineBatchSize: 1024
  ImagineDemonstrationBatchSize: 256
  ImagineContextLength: 8
  ImagineBatchLength: 16
  TrainDynamicsEverySteps: 1
  TrainAgentEverySteps: 1
  UseDemonstration: False
  SaveEverySteps: 20000

Models:
  WorldModel:
    InChannels: 3
    TransformerMaxLength: 64
    TransformerHiddenDim: 256
    TransformerNumLayers: 2
    TransformerNumHeads: 8
    EncoderType: "mlp"
    InputDim: 1
    HiddenDim: 256

  Agent:
    NumLayers: 2
    HiddenDim: 256
    Gamma: 0.99
    Lambda: 0.95
    EntropyCoef: 3E-4

Wandb:
  Project: ""